# Site settings
name: Sławomir Śledź
description: "Big Data and Scala enthusiast"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  ssledz
facebook_username: slawkoo83
twitter_username: ssledz83
linkedin_username: sławomir-śledź-aa857193
stack_of_username: 3726554/slavik
blog_url: "https://ssledz.github.io"
email: slawomir.sledz@gmail.com
public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars3.githubusercontent.com/u/3630870"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
